### PR TITLE
Shop logic

### PR DESCRIPTION
**Pull request by HellenTamara**
Implemented the form for purchase and it displays only the not purchased items

### CODE REVIEW

**Review by Samour621 — APPROVED** [review]
LGTM

**Review by gosuz — APPROVED** [review]
LGTM thanks so much Hellen

**Review by Samour621 — APPROVED** [review]
lgtm

**Review by Samour621 — APPROVED** [review]
LGTM

**Review by AKW9 — APPROVED** [review]

**Pull request merged**
